[features]
seeds = false
skip-lint = false
[programs.localnet]
little_bites_events = "E12wjANt2B7oUzucZ6jnfoLbymFmtC3UhUQn7HPaBrGr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
